name: Build APT Repository Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      COS_REGION: guangzhou
      TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
      TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Sileo
        env:
          COS_BUCKET: sileo2-1302990626
        run: |
          npm install --omit=dev
          npm run build

          dpkg-scanpackages -m ./debs > Packages

          sed -i 's/Section: Packaging/Section: 应用程序/g' Packages
          sed -i 's/Section: Tweak Injection/Section: 插件/g' Packages
          sed -i 's/Author: YKP/Author: 全场景设备智控方案/g' Packages

          # sed -i 's#./debs/#https://debs-1302990626.cos.ap-guangzhou.myqcloud.com/#g' Packages
          sed -i 's#./debs/#debs/#g' Packages

          bzip2 -c Packages > Packages.bz2

          node app.js

      - name: Cydia
        env:
          COS_BUCKET: cydia2-1302990626
        run: |
          # awk -v RS="" '/Package: com\.sky\.ykpro/ && /Architecture: iphoneos-arm\n/ {print $0 "\n"}' Packages > Packages.tmp && mv Packages.tmp Packages

          find debs/ -type f ! -name "*iphoneos-arm.deb" -delete

          bzip2 -c Packages > Packages.bz2

          node app.js

      - name: Commit changes
        if: false
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: Packages.bz2
